### ISSUE TITLE
S3 EXPORT

### ISSUE THREAD

**Issue by abhi-dwivedi** [ianneub/elasticsearch-to-s3#3]
Hi

How can we export bulk index in one go? what should be the command?

**Comment by ianneub** [comment]
With docker installed you should be able to run the command as seen in the readme:

Replace `my.elasticsearch.server.com` with the ip address or hostname of your ES server, `my-index` with the index you want to dump and `my-bucket` with the S3 bucket you want to dump to. You may need to add environment variables for `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` if the container cannot infer this information.

`docker run --rm -e "ES_URL=http://my.elasticsearch.server.com/" -e "ES_INDEX=my-index" -e "S3_BUCKET=my-bucket" -e "S3_KEY=es-test.gz" ianneub/elasticsearch-to-s3`
